import {
  DEFAULT_COLORS,
  DEFAULT_FONT_SIZE,
  DEFAULT_RADII,
  DEFAULT_SPACING,
  type Theme,
} from "../tokens";

export const green: Theme = {
  name: "green",
  colors: {
    ...DEFAULT_COLORS,
    background: "#F1F8F4",
    surface: "#FFFFFF",
    surfaceElevated: "#DCF8C6",
    surfaceMuted: "#F1F8F4",
    primary: "#15803D",
    primaryText: "#FFFFFF",
    secondary: "#22C55E",
    secondaryMuted: "rgba(34, 197, 94, 0.12)",
    accent: "#22C55E",
    accentMuted: "rgba(34, 197, 94, 0.12)",
    text: "#14532D",
    textMuted: "#4B5563",
    border: "#D1FAE5",
    borderVariant: "#BBF7D0",
    statusReceived: "#94A3B8",
    statusCutting: "#F59E0B",
    statusStitching: "#3B82F6",
    statusTrial: "#8B5CF6",
    statusFinishing: "#10B981",
    statusReady: "#22C55E",
    statusDelivered: "#15803D",
    statusCancelled: "#DC2626",
    statusOverdue: "#DC2626",
  },
  spacing: { ...DEFAULT_SPACING },
  radii: { ...DEFAULT_RADII },
  fontSize: { ...DEFAULT_FONT_SIZE },
};
