import {
  DEFAULT_COLORS,
  DEFAULT_FONT_SIZE,
  DEFAULT_RADII,
  DEFAULT_SPACING,
  type Theme,
} from "../tokens";

export const vibrant: Theme = {
  name: "vibrant",
  colors: {
    ...DEFAULT_COLORS,
    background: "#FFF7E6",
    surface: "#FFFFFF",
    surfaceElevated: "#FFF0D4",
    surfaceMuted: "#FFF7E6",
    primary: "#B23A48",
    primaryText: "#FFFFFF",
    secondary: "#2E86AB",
    secondaryMuted: "rgba(46, 134, 171, 0.12)",
    accent: "#2E86AB",
    accentMuted: "rgba(46, 134, 171, 0.12)",
    text: "#1F2937",
    textMuted: "#6B5E5E",
    border: "#F0E2C8",
    borderVariant: "#E8D5B0",
    statusReceived: "#F4A261",
    statusCutting: "#E76F51",
    statusStitching: "#2E86AB",
    statusTrial: "#9C6ADE",
    statusFinishing: "#0E9594",
    statusReady: "#2A9D8F",
    statusDelivered: "#1B7A4F",
    statusCancelled: "#C0392B",
    statusOverdue: "#B23A48",
  },
  spacing: { ...DEFAULT_SPACING },
  radii: { ...DEFAULT_RADII },
  fontSize: { ...DEFAULT_FONT_SIZE },
};
